### ISSUE TITLE
Predict on test set

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Brain_tumour_diagnostic#10]
As a developer I can use the machine learning model to make predictions on unseen data so that I can show the utility of the model

### Acceptance Criteria

- Predictions can be made on the test set

### Tasks

- [x] Load test set
- [x] Load model
- [x] Predict probabilities of each label
- [x] Show most probable label
