### ISSUE TITLE
Brain Tumour Diagnostic Page

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Brain_tumour_diagnostic#15]
As a user I can make predictions on MRI scans so that I can test the performance of the model

### Acceptance Criteria

-  Brain tumour diagnostic page is added to streamlit app
- Images can be uploaded, and a prediction can be made using the image

### Tasks

- [x] Create machine learning performance page
- [x] Add the page to the streamlit app
- [x] Create a function to load the images and make predictions using the model
- [x] Create a function to plot the probabilities
