### ISSUE TITLE
Image sizes notebook

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Brain_tumour_diagnostic#4]
As a developer I can analyze the size of images in the training dataset, so that I can assign an suitable value to standardize the image sizes for machine learning

### Acceptance Criteria

- Image size distribution is shown
- Image shape embeddings are saved as pkl file

### Tasks

- [x] Display plot of image size distrubutions
- [x] Calculate average image size
- [x] Save image size embeddings
